// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bingit.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230627163658_Create_Table_TXTLOPHOC")]
    partial class Create_Table_TXTLOPHOC
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.8");

            modelBuilder.Entity("Bingit.Models.TXTLOPHOC", b =>
                {
                    b.Property<string>("MALOPHOC")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("TENLOPHOC")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("MALOPHOC");

                    b.ToTable("TXTLOPHOC");
                });

            modelBuilder.Entity("Bingit.Models.TXTSINHVIEN", b =>
                {
                    b.Property<int?>("MASV")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MALOP")
                        .HasMaxLength(20)
                        .HasColumnType("INTEGER");

                    b.Property<string>("NAME")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("MASV");

                    b.ToTable("TXTSINHVIEN");
                });
#pragma warning restore 612, 618
        }
    }
}
